version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: telehealth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdF1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:asdF1234@db:5432/telehealth
    restart: unless-stopped

volumes:
  postgres_data:
