# Generated by Django 2.2 on 2024-06-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='booking_date',
            new_name='booking_day',
        ),
    ]
