# Generated by Django 2.2 on 2024-06-19 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medai', '0003_auto_20240619_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='booking_day',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='booking_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'scheduled'), ('cancelled', 'cancelled'), ('ongoing', 'ongoing'), ('closed', 'closed')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booking_time', models.TimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='availabilities', to='medai.Doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
