# Generated by Django 2.2 on 2024-06-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medai', '0004_auto_20240619_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
