# Generated by Django 2.2 on 2024-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medai', '0006_delete_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('cancelled', 'cancelled'), ('ongoing', 'ongoing'), ('closed', 'closed')], default='scheduled', max_length=20),
        ),
    ]
